name: Convert Icons to Xcassets

on:
  push:
    branches:
      - develop
    paths:
      - 'Sources/BUIDesignSystemiOS/PNGIcons/**'
  workflow_dispatch:

permissions:
  contents: write  # Required for committing files back to the repository

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to ensure we have the complete repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Debug repository structure
        run: |
          echo "Current directory structure:"
          find . -type d | sort
          echo "PNGIcons directory content:"
          find ./Sources -name "PNGIcons" -type d -exec ls -la {} \; || echo "PNGIcons directory not found"

      - name: Run conversion script
        id: run_script
        run: |
          echo "Running script as $(whoami) at $(date)"
          echo "Current working directory: $(pwd)"
          
          # Run with verbose output
          python Sources/buildAssets-script.py
          SCRIPT_EXIT_CODE=$?
          
          # Debug results regardless of script exit code
          echo "Script exit code: $SCRIPT_EXIT_CODE"
          echo "Checking for xcassets:"
          find . -name "*.xcassets" -type d || echo "No xcassets directories found"
          
          # List any xcassets content if it exists
          for xcassets_dir in $(find . -name "*.xcassets" -type d); do
            echo "Content of $xcassets_dir:"
            find "$xcassets_dir" -type f | sort
          done
          
          # Exit with the script's exit code
          if [ $SCRIPT_EXIT_CODE -ne 0 ]; then
            echo "Script failed"
            exit 1
          fi

      - name: Manual git operations if xcassets exists
        run: |
          # Check if xcassets directory exists
          if [ -d "BUI-Icons.xcassets" ]; then
            echo "Found BUI-Icons.xcassets directory, proceeding with git operations"
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            
            git add BUI-Icons.xcassets/
            
            # Check if there are changes to commit
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Update iOS app icons [skip ci]"
              git push origin develop
              echo "Changes pushed successfully"
            fi
          else
            echo "BUI-Icons.xcassets directory not found"
            echo "Current directories:"
            find . -maxdepth 2 -type d
            exit 1
          fi
