name: Convert Icons to Xcassets

on:
  push:
    branches:
      - develop
    paths:
      - 'Sources/BUIDesignSystemiOS/PNGIcons/**'
  workflow_dispatch:

permissions:
  contents: write  # Required for committing files back to the repository

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: List current directory contents
        run: ls -al

      - name: List Sources directory contents before script execution
        run: |
          ls -al Sources
          ls -al Sources/BUIDesignSystemiOS/PNGIcons || echo "PNGIcons directory not found"

      - name: Run conversion script
        id: run_script
        run: |
          echo "Running script as $(whoami) at $(date)"
          echo "Script location: Sources/buildAssets-script.py"
          
          set -x  # Enable debugging
          python Sources/buildAssets-script.py > script_output.log 2>&1
          SCRIPT_EXIT_CODE=$?
          cat script_output.log
          set +x  # Disable debugging
          
          # Check for successful execution
          if [ $SCRIPT_EXIT_CODE -ne 0 ]; then
            echo "Script failed to execute successfully"
            exit 1
          fi

      - name: List directory contents after script execution
        run: |
          find . -name "*.xcassets" -type d | xargs ls -la

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update iOS app icons [skip ci]"
          branch: develop
          file_pattern: "**/*.xcassets/**"  # This pattern will match any .xcassets directories and their contents
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
